# Generated by Django 5.2.1 on 2025-05-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_usermonster'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonster',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_by', to='login_app.monster'),
        ),
    ]
