# Generated by Django 5.2.1 on 2025-05-15 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_usermonster_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creator_ready', models.BooleanField(default=False)),
                ('is_opponent_ready', models.BooleanField(default=False)),
                ('is_started', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles_created', to=settings.AUTH_USER_MODEL)),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles_joined', to=settings.AUTH_USER_MODEL)),
                ('party_a', models.ManyToManyField(blank=True, related_name='battle_as_a', to='login_app.usermonster', verbose_name='パーティA')),
                ('party_b', models.ManyToManyField(blank=True, related_name='battle_as_b', to='login_app.usermonster', verbose_name='パーティB')),
            ],
        ),
    ]
