# Generated by Django 5.2.1 on 2025-05-15 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_battle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Battle',
        ),
    ]
