# Generated by Django 5.2.1 on 2025-05-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_delete_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='monsters/back/', verbose_name='後ろ姿_画像'),
        ),
        migrations.AddField(
            model_name='monster',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='monsters/front/', verbose_name='前向き姿_画像'),
        ),
        migrations.AlterField(
            model_name='usermonster',
            name='level',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
