# Generated by Django 5.2.1 on 2025-05-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_monster_image_back_monster_image_front_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermonster',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
