# Generated by Django 5.2.1 on 2025-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_alter_usermonster_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermonster',
            name='level',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
