# Generated by Django 5.2.1 on 2025-05-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_alter_usermonster_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='monsters/back/'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='monsters/front/'),
        ),
        migrations.AlterField(
            model_name='monster',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monster',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='monster',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monsters', to='login_app.skill'),
        ),
    ]
