# Generated by Django 5.2.1 on 2025-05-20 06:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_alter_monster_image_back_alter_monster_image_front_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermonster',
            options={'ordering': ['template__name']},
        ),
        migrations.RenameField(
            model_name='usermonster',
            old_name='exp',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='usermonster',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermonster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usermonster',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usermonster',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_app.monster'),
        ),
        migrations.AlterField(
            model_name='usermonster',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usermonster',
            unique_together={('user', 'template')},
        ),
    ]
