# Generated by Django 5.2.1 on 2025-05-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_alter_usermonster_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='base_defense',
            new_name='base_defence',
        ),
    ]
