# Generated by Django 5.2.1 on 2025-05-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_rename_base_defense_monster_base_defence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='defense_per_level',
            new_name='defence_per_level',
        ),
    ]
