# Generated by Django 5.2.1 on 2025-05-22 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0015_timeattackrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='loss_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='win_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='best_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='login_app.timeattackrecord', verbose_name='ベストタイム記録'),
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
